-- Backup & Restore support (js/admin_backup_tables.js).
--
-- 1. Identity columns accept explicit ids.
--    staff_roster.staff_id and reservation_staff_assignments.assignment_id were
--    created GENERATED ALWAYS, and Postgres rejects any INSERT that supplies a
--    value for such a column ("cannot insert a non-DEFAULT value into column").
--    A restore has to put the original ids back — other rows reference them
--    (reservation_staff_assignments.roster_staff_id -> staff_roster.staff_id).
--    BY DEFAULT keeps ids auto-generated for every normal insert; the app never
--    supplies one.
--
-- 2. backup_resync_sequences(): run by the restore after it writes data.
--    - Moves the two identity sequences forward to at least max(id), so the next
--      insert after restoring into an empty database doesn't collide with a
--      restored row.
--    - Rebuilds reservation_number_counters from reservations.reservation_number.
--      That table has RLS on with no policies (see
--      20260707_fix_reservation_number_counters_rls.sql), so the client can
--      neither back it up nor restore it; without a rebuild, the next booking
--      on a date would be numbered ELI-YYMMDD-001 again and duplicate an
--      existing reservation number.
--    Only ever moves values FORWARD, so it is safe to run at any time.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.staff_roster
  alter column staff_id set generated by default;

alter table public.reservation_staff_assignments
  alter column assignment_id set generated by default;


create or replace function public.backup_resync_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_seq  text;
  v_max  bigint;
  v_last bigint;
begin
  if public.get_my_role() is distinct from 'admin' then
    raise exception 'Only an admin can resync sequences.' using errcode = '42501';
  end if;

  -- staff_roster.staff_id
  v_seq := pg_get_serial_sequence('public.staff_roster', 'staff_id');
  select max(staff_id) into v_max from public.staff_roster;
  v_last := pg_sequence_last_value(v_seq::regclass);
  if v_max is not null and (v_last is null or v_last < v_max) then
    perform setval(v_seq, v_max, true);
  end if;

  -- reservation_staff_assignments.assignment_id
  v_seq := pg_get_serial_sequence('public.reservation_staff_assignments', 'assignment_id');
  select max(assignment_id) into v_max from public.reservation_staff_assignments;
  v_last := pg_sequence_last_value(v_seq::regclass);
  if v_max is not null and (v_last is null or v_last < v_max) then
    perform setval(v_seq, v_max, true);
  end if;

  -- reservation_number_counters: ELI-YYMMDD-NNN -> (date, highest NNN)
  insert into public.reservation_number_counters (event_date, last_sequence)
  select
    to_date(substr(reservation_number, 5, 6), 'YYMMDD'),
    max(substr(reservation_number, 12)::integer)
  from public.reservations
  where reservation_number ~ '^ELI-[0-9]{6}-[0-9]{1,9}$'
  group by 1
  on conflict (event_date) do update
    set last_sequence = greatest(
      public.reservation_number_counters.last_sequence,
      excluded.last_sequence
    );
end;
$$;

revoke all on function public.backup_resync_sequences() from public, anon;
grant execute on function public.backup_resync_sequences() to authenticated;
